### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by oandregal** [Automattic/biab-cli#1]
Document or provide a script to do it automatically:

* download in `/opt/bloginabox`
* assign user/group: `sudo chown -R pi:pi /opt/bloginabox/`
* give `biab` exec permissions: `sudo chmod +x /opt/bloginabox/biab`
* install node environment

```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
nvm install v6.9.5
sudo ln -s /home/pi/.nvm/versions/node/v6.9.5/bin/node /usr/bin/node
sudo ln -s /home/pi/.nvm/versions/node/v6.9.5/bin/npm /usr/bin/npm
```
* activate plugin in your WordPress installation
* go to the settings page in the plugin main screen at `http://<your-blog-in-a-box>/wp-admin/admin.php?page=biab-plugin`, modify at your convenience, and save (this creates the settings file for the first time).

**Comment by johngodley** [comment]
Closing this as it's all auto-configured now!
