### ISSUE TITLE
Better boot and setup images

### ISSUE THREAD

**Issue by johngodley** [Automattic/biab-cli#2]
Some images are shown on the Pi attached screen during bootup and setup:

- https://github.com/tinkertinker/biab-cli/blob/master/boot/biab.jpg - shown when the Pi boots
- https://github.com/tinkertinker/biab-cli/blob/master/boot/biab-setup.jpg - shown the first time the Pi boots and indicates that stuff is being configured

These need to be made better.

Note the images should be 1080p

**Comment by jasmussen** [comment]
These are a little uninspired, but hopefully you can use them and we can improve them later if need be:

![boot](https://cloud.githubusercontent.com/assets/1204802/22972854/b60f1884-f37b-11e6-93cd-1d17058c306a.png)

![setting up](https://cloud.githubusercontent.com/assets/1204802/22972858/b792e85c-f37b-11e6-958a-6b74a156cc24.png)

**Comment by johngodley** [comment]
Perfect, it looks great on the boot screen!
